/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MovieInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'isPremium' : IDL.Bool,
  'cast' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isTopRated' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'videoUrl' : IDL.Text,
  'isTrending' : IDL.Bool,
});
export const Movie = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'isPremium' : IDL.Bool,
  'cast' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isTopRated' : IDL.Bool,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'videoUrl' : IDL.Text,
  'isTrending' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WatchEntry = IDL.Record({
  'movieId' : IDL.Nat,
  'progressSeconds' : IDL.Nat,
  'lastWatched' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'isPremium' : IDL.Bool,
  'userId' : IDL.Text,
  'subscriptionExpiry' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'myList' : IDL.Vec(IDL.Nat),
  'watchHistory' : IDL.Vec(WatchEntry),
});
export const SubscriptionPlan = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'durationMonths' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Subscription = IDL.Record({
  'startedAt' : IDL.Int,
  'expiresAt' : IDL.Int,
  'planId' : IDL.Text,
  'userId' : IDL.Text,
  'isActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMovie' : IDL.Func([MovieInput], [Movie], []),
  'addToMyList' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createOrUpdateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UserProfile],
      [],
    ),
  'deleteMovie' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFreeMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMovie' : IDL.Func([IDL.Nat], [IDL.Opt(Movie)], ['query']),
  'getMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMoviesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'getMyList' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'getPremiumMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getSubscriptionPlans' : IDL.Func([], [IDL.Vec(SubscriptionPlan)], ['query']),
  'getTopRatedMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getTrendingMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getUserSubscription' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Subscription)],
      ['query'],
    ),
  'getWatchHistory' : IDL.Func([IDL.Text], [IDL.Vec(WatchEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromMyList' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'subscribe' : IDL.Func([IDL.Text, IDL.Text], [Subscription], []),
  'updateMovie' : IDL.Func([IDL.Nat, MovieInput], [IDL.Opt(Movie)], []),
  'updateWatchProgress' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MovieInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'isPremium' : IDL.Bool,
    'cast' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isTopRated' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'videoUrl' : IDL.Text,
    'isTrending' : IDL.Bool,
  });
  const Movie = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'isPremium' : IDL.Bool,
    'cast' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isTopRated' : IDL.Bool,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'videoUrl' : IDL.Text,
    'isTrending' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WatchEntry = IDL.Record({
    'movieId' : IDL.Nat,
    'progressSeconds' : IDL.Nat,
    'lastWatched' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'isPremium' : IDL.Bool,
    'userId' : IDL.Text,
    'subscriptionExpiry' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'myList' : IDL.Vec(IDL.Nat),
    'watchHistory' : IDL.Vec(WatchEntry),
  });
  const SubscriptionPlan = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'durationMonths' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Subscription = IDL.Record({
    'startedAt' : IDL.Int,
    'expiresAt' : IDL.Int,
    'planId' : IDL.Text,
    'userId' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMovie' : IDL.Func([MovieInput], [Movie], []),
    'addToMyList' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createOrUpdateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UserProfile],
        [],
      ),
    'deleteMovie' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFreeMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMovie' : IDL.Func([IDL.Nat], [IDL.Opt(Movie)], ['query']),
    'getMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMoviesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'getMyList' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'getPremiumMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getTopRatedMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getTrendingMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getUserSubscription' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Subscription)],
        ['query'],
      ),
    'getWatchHistory' : IDL.Func([IDL.Text], [IDL.Vec(WatchEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromMyList' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'subscribe' : IDL.Func([IDL.Text, IDL.Text], [Subscription], []),
    'updateMovie' : IDL.Func([IDL.Nat, MovieInput], [IDL.Opt(Movie)], []),
    'updateWatchProgress' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };