/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Movie {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'thumbnailUrl' : string,
  'isPremium' : boolean,
  'cast' : Array<string>,
  'createdAt' : bigint,
  'description' : string,
  'isTopRated' : boolean,
  'category' : string,
  'rating' : number,
  'videoUrl' : string,
  'isTrending' : boolean,
}
export interface MovieInput {
  'title' : string,
  'duration' : string,
  'thumbnailUrl' : string,
  'isPremium' : boolean,
  'cast' : Array<string>,
  'description' : string,
  'isTopRated' : boolean,
  'category' : string,
  'rating' : number,
  'videoUrl' : string,
  'isTrending' : boolean,
}
export interface Subscription {
  'startedAt' : bigint,
  'expiresAt' : bigint,
  'planId' : string,
  'userId' : string,
  'isActive' : boolean,
}
export interface SubscriptionPlan {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'durationMonths' : bigint,
  'price' : bigint,
}
export interface UserProfile {
  'isPremium' : boolean,
  'userId' : string,
  'subscriptionExpiry' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'myList' : Array<bigint>,
  'watchHistory' : Array<WatchEntry>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchEntry {
  'movieId' : bigint,
  'progressSeconds' : bigint,
  'lastWatched' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMovie' : ActorMethod<[MovieInput], Movie>,
  'addToMyList' : ActorMethod<[string, bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[string], boolean>,
  'createOrUpdateUserProfile' : ActorMethod<
    [string, string, string],
    UserProfile
  >,
  'deleteMovie' : ActorMethod<[bigint], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFreeMovies' : ActorMethod<[], Array<Movie>>,
  'getMovie' : ActorMethod<[bigint], [] | [Movie]>,
  'getMovies' : ActorMethod<[], Array<Movie>>,
  'getMoviesByCategory' : ActorMethod<[string], Array<Movie>>,
  'getMyList' : ActorMethod<[string], Array<bigint>>,
  'getPremiumMovies' : ActorMethod<[], Array<Movie>>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getTopRatedMovies' : ActorMethod<[], Array<Movie>>,
  'getTrendingMovies' : ActorMethod<[], Array<Movie>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getUserSubscription' : ActorMethod<[string], [] | [Subscription]>,
  'getWatchHistory' : ActorMethod<[string], Array<WatchEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromMyList' : ActorMethod<[string, bigint], boolean>,
  'searchMovies' : ActorMethod<[string], Array<Movie>>,
  'subscribe' : ActorMethod<[string, string], Subscription>,
  'updateMovie' : ActorMethod<[bigint, MovieInput], [] | [Movie]>,
  'updateWatchProgress' : ActorMethod<[string, bigint, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];